import sys
import os
from werkzeug.security import generate_password_hash

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from flask import Flask
from flask_pymongo import PyMongo
from services.register_service import RegisterService
from services.interest_service import InterestService

app = Flask(__name__)
app.config["MONGO_URI"] = "mongodb://localhost:27017/pairup_db"

mongo = PyMongo(app)
app.mongo = mongo  


def seed_user(data, interest_data=None):
    db = app.mongo.db
    register_service = RegisterService(db)
    interest_service = InterestService(db)

    print(f"Seeding user: {data['email']}")

    if 'role' not in data:
        data['role'] = 'user'

    if data['role'] == 'admin':
        existing = db.users.find_one({'email': data['email']})
        if existing:
            print(f"Admin user {data['email']} already exists. Skipping.")
            return

        admin_doc = {
            'name': data['name'],
            'email': data['email'],
            'password': generate_password_hash(data['password']),
            'role': 'admin',
            'status': 'active',
            'interests_completed': True,  
            'photo': data.get('photo', '/img/defaultadmin.jpg'), 
        }
        db.users.insert_one(admin_doc)
        print(f"Seeded admin user: {data['email']}")
        return

    result, status = register_service.register_user(data)
    print(f"  Register status: {status}, message: {result['message']}")

    if status == 200 and interest_data:
        result, status = interest_service.save_interests(data["email"], interest_data)
        print(f"  Interests status: {status}, message: {result['message']}")

    print()


def seed_all():
    admins_to_seed = [
        {
            "name": "Super Admin",
            "email": "admin@example.com",
            "password": "admin123",
            "role": "admin",
            "photo": "/img/defaultadmin.jpg", 
        },
    ]

    users_to_seed = [
        {"name": "Sujita Sharma", "email": "sujita@example.com", "password": "sujita123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'4\"", "maritalStatus": "Single", "education": "Masters", "profession": "Software Engineer", "personality": ["Introvert", "Creative"], "caption": "Love mountains and books.", "interests": ["Reading", "Hiking", "Photography", "Coding"]}},
        {"name": "Nandita Rai", "email": "nandita@example.com", "password": "nandita123", "details": {"age": 25, "gender": "Female", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Calm", "Patient"], "caption": "Passionate about education.", "interests": ["Teaching", "Gardening", "Meditation", "Traveling"]}},
        {"name": "Samriddhi Thapa", "email": "samriddhi@example.com", "password": "samriddhi123", "details": {"age": 27, "gender": "Female", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'5\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Confident", "Empathetic"], "caption": "Helping people is my passion.", "interests": ["Volunteering", "Yoga", "Cooking", "Reading"]}},
        {"name": "Kush Gurung", "email": "kush@example.com", "password": "kush123", "details": {"age": 29, "gender": "Male", "religion": "Hindu", "location": "Butwal, Nepal", "latitude": 27.7000, "longitude": 83.4500, "height": "5'8\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Calm", "Friendly"], "caption": "Making learning fun.", "interests": ["Teaching", "Football", "Music", "Travel"]}},
        {"name": "Lav Singh", "email": "lav@example.com", "password": "lav123", "details": {"age": 30, "gender": "Male", "religion": "Hindu", "location": "Janakpur, Nepal", "latitude": 26.7097, "longitude": 85.9220, "height": "5'9\"", "maritalStatus": "Single", "education": "Masters", "profession": "Engineer", "personality": ["Logical", "Adventurous"], "caption": "Engineering the future.", "interests": ["Hiking", "Reading", "Technology", "Travel"]}},
        {"name": "Nishan KC", "email": "nishan@example.com", "password": "nishan123", "details": {"age": 28, "gender": "Male", "religion": "Buddhist", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'10\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Compassionate", "Calm"], "caption": "Health is wealth.", "interests": ["Yoga", "Cooking", "Volunteering", "Reading"]}},
        {"name": "Nikhil Thapa", "email": "nikhil@example.com", "password": "nikhil123", "details": {"age": 27, "gender": "Male", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'9\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Developer", "personality": ["Techie", "Friendly"], "caption": "Coding my dreams.", "interests": ["Programming", "Gaming", "Music", "Hiking"]}},
        {"name": "Binam Gurung", "email": "binam@example.com", "password": "binam123", "details": {"age": 25, "gender": "Male", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'7\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Designer", "personality": ["Creative", "Calm"], "caption": "Designing a colorful life.", "interests": ["Drawing", "Photography", "Traveling", "Music"]}},
        {"name": "Palsang Lama", "email": "palsang@example.com", "password": "palsang123", "details": {"age": 26, "gender": "Male", "religion": "Buddhist", "location": "Bhaktapur, Nepal", "latitude": 27.6726, "longitude": 85.4278, "height": "5'8\"", "maritalStatus": "Single", "education": "Masters", "profession": "Researcher", "personality": ["Curious", "Analytical"], "caption": "Exploring science and nature.", "interests": ["Research", "Reading", "Traveling", "Yoga"]}},
        {"name": "Sankalpa Rai", "email": "sankalpa@example.com", "password": "sankalpa123", "details": {"age": 24, "gender": "Male", "religion": "Hindu", "location": "Biratnagar, Nepal", "latitude": 26.4550, "longitude": 87.2718, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Journalist", "personality": ["Inquisitive", "Creative"], "caption": "Telling stories.", "interests": ["Writing", "Photography", "Travel", "Reading"]}},
        {"name": "Alice Sharma", "email": "alice@example.com", "password": "alice123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'4\"", "maritalStatus": "Single", "education": "Masters", "profession": "Software Engineer", "personality": ["Introvert", "Creative"], "caption": "Love mountains and books.", "interests": ["Reading", "Hiking", "Photography", "Coding"]}},
        {"name": "Rahul Joshi", "email": "rahul@example.com", "password": "rahul123", "details": {"age": 29, "gender": "Male", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'9\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Civil Engineer", "personality": ["Adventurous", "Calm"], "caption": "Enjoy life one hike at a time.", "interests": ["Hiking", "Traveling", "Photography", "Music"]}},
        {"name": "Sita Rana", "email": "sita@example.com", "password": "sita123", "details": {"age": 24, "gender": "Female", "religion": "Christian", "location": "Biratnagar, Nepal", "latitude": 26.4550, "longitude": 87.2718, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Optimistic", "Grounded"], "caption": "Passionate about teaching.", "interests": ["Teaching", "Cooking", "Travel", "Reading"]}},
        {"name": "Prakash Thapa", "email": "prakash@example.com", "password": "prakash123", "details": {"age": 31, "gender": "Male", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'10\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Confident", "Empathetic"], "caption": "Committed to helping others.", "interests": ["Volunteering", "Reading", "Cooking", "Yoga"]}},
        {"name": "Maya KC", "email": "maya@example.com", "password": "maya123", "details": {"age": 27, "gender": "Female", "religion": "Hindu", "location": "Dharan, Nepal", "latitude": 26.8123, "longitude": 87.2836, "height": "5'5\"", "maritalStatus": "Single", "education": "Masters", "profession": "Artist", "personality": ["Creative", "Calm"], "caption": "Art is my life.", "interests": ["Painting", "Photography", "Traveling", "Meditation"]}},
        {"name": "Sanjay Gurung", "email": "sanjay@example.com", "password": "sanjay123", "details": {"age": 28, "gender": "Male", "religion": "Hindu", "location": "Butwal, Nepal", "latitude": 27.7000, "longitude": 83.4500, "height": "5'8\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Calm", "Patient"], "caption": "Helping others learn.", "interests": ["Teaching", "Football", "Music", "Reading"]}},
        {"name": "Kumari Rai", "email": "kumari@example.com", "password": "kumari123", "details": {"age": 25, "gender": "Female", "religion": "Buddhist", "location": "Janakpur, Nepal", "latitude": 26.7097, "longitude": 85.9220, "height": "5'2\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Nurse", "personality": ["Kind", "Optimistic"], "caption": "Care is my passion.", "interests": ["Nursing", "Reading", "Cooking", "Traveling"]}},
        {"name": "Niraj Koirala", "email": "niraj@example.com", "password": "niraj123", "details": {"age": 30, "gender": "Male", "religion": "Christian", "location": "Birgunj, Nepal", "latitude": 27.0000, "longitude": 84.8667, "height": "5'11\"", "maritalStatus": "Single", "education": "Masters", "profession": "Engineer", "personality": ["Adventurous", "Logical"], "caption": "Building better tomorrow.", "interests": ["Engineering", "Music", "Travel", "Hiking"]}},
        {"name": "Sushma Lama", "email": "sushma@example.com", "password": "sushma123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Hetauda, Nepal", "latitude": 27.4167, "longitude": 85.0333, "height": "5'3\"", "maritalStatus": "Single", "education": "Masters", "profession": "Researcher", "personality": ["Curious", "Creative"], "caption": "Exploring science and nature.", "interests": ["Research", "Reading", "Photography", "Nature"]}},
        {"name": "Bibek Thapa", "email": "bibek@example.com", "password": "bibek123", "details": {"age": 27, "gender": "Male", "religion": "Hindu", "location": "Dhangadhi, Nepal", "latitude": 28.7017, "longitude": 80.5997, "height": "5'9\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Developer", "personality": ["Techie", "Friendly"], "caption": "Coding my dreams.", "interests": ["Programming", "Gaming", "Music", "Travel"]}},
        {"name": "Nisha Shrestha", "email": "nisha@example.com", "password": "nisha123", "details": {"age": 28, "gender": "Female", "religion": "Hindu", "location": "Bhaktapur, Nepal", "latitude": 27.6726, "longitude": 85.4278, "height": "5'4\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Designer", "personality": ["Creative", "Calm"], "caption": "Designing a colorful life.", "interests": ["Design", "Photography", "Travel", "Music"]}},
        {"name": "Ram KC", "email": "ram@example.com", "password": "ram123", "details": {"age": 29, "gender": "Male", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'10\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Caring", "Calm"], "caption": "Health is wealth.", "interests": ["Yoga", "Reading", "Volunteering", "Cooking"]}},
        {"name": "Sunita Gautam", "email": "sunita@example.com", "password": "sunita123", "details": {"age": 25, "gender": "Female", "religion": "Hindu", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Lawyer", "personality": ["Strong", "Intelligent"], "caption": "Justice for all.", "interests": ["Reading", "Debate", "Travel", "Music"]}},
        {"name": "Dipesh Bhandari", "email": "dipesh@example.com", "password": "dipesh123", "details": {"age": 31, "gender": "Male", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'11\"", "maritalStatus": "Single", "education": "Masters", "profession": "Entrepreneur", "personality": ["Confident", "Ambitious"], "caption": "Building startups.", "interests": ["Business", "Travel", "Music", "Reading"]}},
        {"name": "Manisha Rai", "email": "manisha@example.com", "password": "manisha123", "details": {"age": 27, "gender": "Female", "religion": "Christian", "location": "Biratnagar, Nepal", "latitude": 26.4550, "longitude": 87.2718, "height": "5'4\"", "maritalStatus": "Single", "education": "Masters", "profession": "Journalist", "personality": ["Inquisitive", "Creative"], "caption": "Telling stories.", "interests": ["Writing", "Photography", "Travel", "Reading"]}},
        {"name": "Pradeep Shrestha", "email": "pradeep@example.com", "password": "pradeep123", "details": {"age": 30, "gender": "Male", "religion": "Hindu", "location": "Hetauda, Nepal", "latitude": 27.4167, "longitude": 85.0333, "height": "5'10\"", "maritalStatus": "Single", "education": "Masters", "profession": "Accountant", "personality": ["Organized", "Dependable"], "caption": "Numbers tell the truth.", "interests": ["Accounting", "Reading", "Music", "Travel"]}},
        {"name": "Rita Khatri", "email": "rita@example.com", "password": "rita123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Butwal, Nepal", "latitude": 27.7000, "longitude": 83.4500, "height": "5'5\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Nurse", "personality": ["Caring", "Patient"], "caption": "Healing hands.", "interests": ["Nursing", "Reading", "Cooking", "Music"]}},
        {"name": "Sujan Pandey", "email": "sujan@example.com", "password": "sujan123", "details": {"age": 28, "gender": "Male", "religion": "Buddhist", "location": "Dhangadhi, Nepal", "latitude": 28.7017, "longitude": 80.5997, "height": "5'9\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Developer", "personality": ["Techie", "Creative"], "caption": "Coding the future.", "interests": ["Programming", "Gaming", "Music", "Travel"]}},
        {"name": "Anita Sharma", "email": "anita@example.com", "password": "anita123", "details": {"age": 27, "gender": "Female", "religion": "Hindu", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'4\"", "maritalStatus": "Single", "education": "Masters", "profession": "Researcher", "personality": ["Curious", "Calm"], "caption": "Passionate about science.", "interests": ["Research", "Reading", "Photography", "Travel"]}},
        {"name": "Ramesh Lama", "email": "ramesh@example.com", "password": "ramesh123", "details": {"age": 29, "gender": "Male", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'8\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Empathetic", "Patient"], "caption": "Caring for all.", "interests": ["Volunteering", "Yoga", "Cooking", "Reading"]}},
        {"name": "Sangeeta Rai", "email": "sangeeta@example.com", "password": "sangeeta123", "details": {"age": 25, "gender": "Female", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Kind", "Optimistic"], "caption": "Inspiring young minds.", "interests": ["Teaching", "Gardening", "Reading", "Travel"]}},
        {"name": "Bikash Koirala", "email": "bikash@example.com", "password": "bikash123", "details": {"age": 30, "gender": "Male", "religion": "Hindu", "location": "Birgunj, Nepal", "latitude": 27.0000, "longitude": 84.8667, "height": "5'10\"", "maritalStatus": "Single", "education": "Masters", "profession": "Engineer", "personality": ["Logical", "Adventurous"], "caption": "Building the future.", "interests": ["Engineering", "Hiking", "Travel", "Music"]}},
        {"name": "Prerana Shrestha", "email": "prerana@example.com", "password": "prerana123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Bhaktapur, Nepal", "latitude": 27.6726, "longitude": 85.4278, "height": "5'5\"", "maritalStatus": "Single", "education": "Masters", "profession": "Designer", "personality": ["Creative", "Friendly"], "caption": "Design is my passion.", "interests": ["Design", "Photography", "Travel", "Yoga"]}},
        {"name": "Rajesh Thapa", "email": "rajesh@example.com", "password": "rajesh123", "details": {"age": 27, "gender": "Male", "religion": "Hindu", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'9\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Developer", "personality": ["Techie", "Friendly"], "caption": "Love to code.", "interests": ["Programming", "Gaming", "Music", "Travel"]}},
        {"name": "Manju Gurung", "email": "manju@example.com", "password": "manju123", "details": {"age": 25, "gender": "Female", "religion": "Buddhist", "location": "Lalitpur, Nepal", "latitude": 27.6725, "longitude": 85.3209, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Calm", "Patient"], "caption": "Teaching is my joy.", "interests": ["Teaching", "Music", "Travel", "Reading"]}},
        {"name": "Kiran Rana", "email": "kiran@example.com", "password": "kiran123", "details": {"age": 29, "gender": "Male", "religion": "Hindu", "location": "Butwal, Nepal", "latitude": 27.7000, "longitude": 83.4500, "height": "5'8\"", "maritalStatus": "Single", "education": "Masters", "profession": "Engineer", "personality": ["Logical", "Adventurous"], "caption": "Building dreams.", "interests": ["Engineering", "Hiking", "Travel", "Music"]}},
        {"name": "Sita Magar", "email": "sita.m@example.com", "password": "sitam123", "details": {"age": 28, "gender": "Female", "religion": "Hindu", "location": "Pokhara, Nepal", "latitude": 28.2096, "longitude": 83.9856, "height": "5'4\"", "maritalStatus": "Single", "education": "Masters", "profession": "Doctor", "personality": ["Caring", "Empathetic"], "caption": "Helping others.", "interests": ["Yoga", "Volunteering", "Reading", "Cooking"]}},
        {"name": "Raj Kumar", "email": "rajk@example.com", "password": "rajk123", "details": {"age": 30, "gender": "Male", "religion": "Buddhist", "location": "Kathmandu, Nepal", "latitude": 27.7172, "longitude": 85.324, "height": "5'11\"", "maritalStatus": "Single", "education": "Masters", "profession": "Entrepreneur", "personality": ["Ambitious", "Confident"], "caption": "Building startups.", "interests": ["Business", "Travel", "Music", "Reading"]}},
        {"name": "Laxmi Thapa", "email": "laxmi@example.com", "password": "laxmi123", "details": {"age": 26, "gender": "Female", "religion": "Hindu", "location": "Janakpur, Nepal", "latitude": 26.7097, "longitude": 85.9220, "height": "5'3\"", "maritalStatus": "Single", "education": "Bachelors", "profession": "Teacher", "personality": ["Kind", "Optimistic"], "caption": "Inspiring minds.", "interests": ["Teaching", "Gardening", "Reading", "Travel"]}},
        {"name": "Suman Rai", "email": "suman@example.com", "password": "suman123", "details": {"age": 27, "gender": "Male", "religion": "Hindu", "location": "Biratnagar, Nepal", "latitude": 26.4550, "longitude": 87.2718, "height": "5'9\"", "maritalStatus": "Single", "education": "Masters", "profession": "Engineer", "personality": ["Logical", "Adventurous"], "caption": "Engineering dreams.", "interests": ["Engineering", "Hiking", "Travel", "Music"]}}
    ]


    interests = [
        {"partner_age": "24-30", "partner_gender": "Male", "partner_height": "5'7\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Confident", "Empathetic"], "partner_hobbies": ["Traveling", "Music"], "partner_pets": "Dog lover", "partner_education": "Bachelors+", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "23-28", "partner_gender": "Male", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Optimistic", "Grounded"], "partner_hobbies": ["Cooking", "Hiking"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Teacher", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "22-27", "partner_gender": "Male", "partner_height": "5'6\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Kind", "Patient"], "partner_hobbies": ["Reading", "Traveling"], "partner_pets": "No preference", "partner_education": "Bachelors", "partner_profession": "Teacher", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "29-35", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Caring", "Creative"], "partner_hobbies": ["Cooking", "Music"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Doctor", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-29", "partner_gender": "Female", "partner_height": "5'6\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Creative", "Calm"], "partner_hobbies": ["Photography", "Hiking"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Artist", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "25-31", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Patient", "Kind"], "partner_hobbies": ["Reading", "Music"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Teacher", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "27-33", "partner_gender": "Female", "partner_height": "5'8\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Logical", "Friendly"], "partner_hobbies": ["Traveling", "Hiking"], "partner_pets": "No preference", "partner_education": "Bachelors+", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "23-28", "partner_gender": "Female", "partner_height": "5'2\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Kind", "Optimistic"], "partner_hobbies": ["Cooking", "Reading"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Nurse", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "28-34", "partner_gender": "Female", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Adventurous", "Logical"], "partner_hobbies": ["Music", "Photography"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-29", "partner_gender": "Female", "partner_height": "5'4\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Creative", "Calm"], "partner_hobbies": ["Traveling", "Cooking"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Designer", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "29-35", "partner_gender": "Male", "partner_height": "5'8\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Caring", "Calm"], "partner_hobbies": ["Hiking", "Reading"], "partner_pets": "No preference", "partner_education": "Masters", "partner_profession": "Doctor", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "Maybe"},
        {"partner_age": "23-28", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Strong", "Intelligent"], "partner_hobbies": ["Cooking", "Music"], "partner_pets": "Dog lover", "partner_education": "Bachelors", "partner_profession": "Lawyer", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "28-34", "partner_gender": "Male", "partner_height": "5'10\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Confident", "Ambitious"], "partner_hobbies": ["Traveling", "Music"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Entrepreneur", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-29", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Inquisitive", "Creative"], "partner_hobbies": ["Reading", "Traveling"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Journalist", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "30-35", "partner_gender": "Male", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Organized", "Dependable"], "partner_hobbies": ["Music", "Hiking"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Accountant", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-28", "partner_gender": "Female", "partner_height": "5'4\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Caring", "Patient"], "partner_hobbies": ["Cooking", "Reading"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Nurse", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "27-33", "partner_gender": "Male", "partner_height": "5'8\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Patient", "Friendly"], "partner_hobbies": ["Hiking", "Reading"], "partner_pets": "No preference", "partner_education": "Bachelors", "partner_profession": "Teacher", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "26-31", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Logical", "Calm"], "partner_hobbies": ["Traveling", "Cooking"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Engineer", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "25-30", "partner_gender": "Male", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Adventurous", "Confident"], "partner_hobbies": ["Traveling", "Photography"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Entrepreneur", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-28", "partner_gender": "Female", "partner_height": "5'5\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Kind", "Patient"], "partner_hobbies": ["Music", "Reading"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Teacher", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "28-35", "partner_gender": "Male", "partner_height": "5'10\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Friendly", "Logical"], "partner_hobbies": ["Hiking", "Photography"], "partner_pets": "No preference", "partner_education": "Masters", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "23-29", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Creative", "Optimistic"], "partner_hobbies": ["Cooking", "Traveling"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Designer", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "27-33", "partner_gender": "Male", "partner_height": "5'7\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Organized", "Dependable"], "partner_hobbies": ["Music", "Hiking"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Accountant", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "25-30", "partner_gender": "Female", "partner_height": "5'4\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Strong", "Intelligent"], "partner_hobbies": ["Cooking", "Reading"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Lawyer", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "28-34", "partner_gender": "Male", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Ambitious", "Confident"], "partner_hobbies": ["Traveling", "Music"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Entrepreneur", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-29", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Calm", "Patient"], "partner_hobbies": ["Reading", "Music"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Nurse", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "29-35", "partner_gender": "Male", "partner_height": "5'10\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Confident", "Friendly"], "partner_hobbies": ["Traveling", "Photography"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "23-28", "partner_gender": "Female", "partner_height": "5'2\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Optimistic", "Kind"], "partner_hobbies": ["Cooking", "Traveling"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Teacher", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "26-32", "partner_gender": "Male", "partner_height": "5'8\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Calm", "Logical"], "partner_hobbies": ["Hiking", "Reading"], "partner_pets": "No preference", "partner_education": "Bachelors+", "partner_profession": "Teacher", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "24-29", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Creative", "Patient"], "partner_hobbies": ["Reading", "Cooking"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Journalist", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "30-35", "partner_gender": "Male", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Organized", "Dependable"], "partner_hobbies": ["Music", "Hiking"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Accountant", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "25-30", "partner_gender": "Female", "partner_height": "5'4\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Empathetic", "Optimistic"], "partner_hobbies": ["Yoga", "Reading"], "partner_pets": "Dog lover", "partner_education": "Bachelors", "partner_profession": "Designer", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "28-34", "partner_gender": "Male", "partner_height": "5'10\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Confident", "Adventurous"], "partner_hobbies": ["Sports", "Traveling"], "partner_pets": "Cat lover", "partner_education": "Masters", "partner_profession": "Entrepreneur", "partner_family_type": "Nuclear", "partner_family_values": "Traditional", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "23-29", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Kind", "Patient"], "partner_hobbies": ["Cooking", "Painting"], "partner_pets": "No preference", "partner_education": "Masters", "partner_profession": "Teacher", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "26-32", "partner_gender": "Male", "partner_height": "5'9\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Logical", "Friendly"], "partner_hobbies": ["Hiking", "Music"], "partner_pets": "Dog lover", "partner_education": "Bachelors+", "partner_profession": "Engineer", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "No"},
        {"partner_age": "24-28", "partner_gender": "Female", "partner_height": "5'2\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Creative", "Calm"], "partner_hobbies": ["Reading", "Traveling"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Journalist", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "29-35", "partner_gender": "Male", "partner_height": "5'11\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Patient", "Ambitious"], "partner_hobbies": ["Photography", "Traveling"], "partner_pets": "No preference", "partner_education": "Masters", "partner_profession": "Doctor", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "23-27", "partner_gender": "Female", "partner_height": "5'3\"+", "partner_marital_status": "Single", "partner_religion": "Hindu", "partner_personality": ["Optimistic", "Strong"], "partner_hobbies": ["Cooking", "Music"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Lawyer", "partner_family_type": "Joint", "partner_family_values": "Traditional", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
        {"partner_age": "27-33", "partner_gender": "Male", "partner_height": "5'8\"+", "partner_marital_status": "Single", "partner_religion": "Christian", "partner_personality": ["Organized", "Friendly"], "partner_hobbies": ["Sports", "Reading"], "partner_pets": "Dog lover", "partner_education": "Masters", "partner_profession": "Accountant", "partner_family_type": "Nuclear", "partner_family_values": "Moderate", "partner_living_pref": "Urban", "partner_long_distance": "Maybe"},
        {"partner_age": "25-30", "partner_gender": "Female", "partner_height": "5'5\"+", "partner_marital_status": "Single", "partner_religion": "Buddhist", "partner_personality": ["Calm", "Kind"], "partner_hobbies": ["Painting", "Yoga"], "partner_pets": "Cat lover", "partner_education": "Bachelors", "partner_profession": "Nurse", "partner_family_type": "Joint", "partner_family_values": "Moderate", "partner_living_pref": "Flexible", "partner_long_distance": "No"},
    ]


    for admin in admins_to_seed:
        seed_user(admin)  

    for user, interest_data in zip(users_to_seed, interests):
        seed_user(user, interest_data)


if __name__ == "__main__":
    with app.app_context():
        seed_all()



     
  